public class p3 {
    public static void main (String[] args) {
        int sum = 0;
        int i = 1;
        int fib1 = 1;
        int fib2 = 1;
        int number = 4000000;

        while (i < number) {
            if (i % 2 == 0) {
                sum += i;
            }
            fib2 = fib1;
            fib1 = i;
            i = fib1 + fib2;
        }

        System.out.println("The sum of all even numbered Fibonacci less than " + number + " is: " + sum);
    }


    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    //
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
}